"""add warehouse field

Revision ID: d3c2b1a09876
Revises: 9acc01ec754f
Create Date: 2026-07-04 10:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c2b1a09876'
down_revision = '9acc01ec754f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paquetes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_paquetes_warehouse'), ['warehouse'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paquetes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paquetes_warehouse'))
        batch_op.drop_column('warehouse')
    # ### end Alembic commands ###
