"""Añadir indices de rendimiento

Revision ID: f0f10c160165
Revises: 
Create Date: 2026-06-04 00:39:59.599340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f10c160165'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_fecha_emision'), ['fecha_emision'], unique=False)

    with op.batch_alter_table('paquetes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paquetes_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paquetes_estado_rastreo'), ['estado_rastreo'], unique=False)
        batch_op.create_index(batch_op.f('ix_paquetes_numero_seguimiento'), ['numero_seguimiento'], unique=False)
        batch_op.create_index(batch_op.f('ix_paquetes_tipo_envio'), ['tipo_envio'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paquetes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paquetes_tipo_envio'))
        batch_op.drop_index(batch_op.f('ix_paquetes_numero_seguimiento'))
        batch_op.drop_index(batch_op.f('ix_paquetes_estado_rastreo'))
        batch_op.drop_index(batch_op.f('ix_paquetes_cliente_id'))

    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_fecha_emision'))
        batch_op.drop_index(batch_op.f('ix_facturas_estado'))
        batch_op.drop_index(batch_op.f('ix_facturas_cliente_id'))

    # ### end Alembic commands ###
